### ISSUE TITLE
Phishing Attack 

### ISSUE THREAD

**Issue by MithOOnn** [hashdit/hashdit#10]
0xBd6950E133ddfD72F19A90a755BaB3Da03260cc1

This is the address who hacked my wallet. Please action for him please. He set my account in autobot. 
![Screenshot_2024-01-23-04-19-23-24_08800057d42e3b72e31ae4fd4c41ba57](https://github.com/hashdit/hashdit/assets/126584786/688e4c85-ac97-4dd2-91a7-81a7cb473742)

**Comment by Karlitos88** [comment]
0xBd6950E133ddfD72F19A90a755BaB3Da03260cc1
TheNewFactoryArt.&Content.Red
Juancarloss1977
Karlitos88/cli
Bscscan.com
Hashdit/hashdit#5-#10
Hashdit identifyng bigeyes space domain as unsafe
4:19:25

Barcelona 21:55
Viernes 23 Febrero 2024
Juan carlos santos ferreiros

**Comment by Bendy127** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to Mr John a whitehathacker who helped me recover all of it message him on telegram too t.me/Whitehathacker217

**Comment by Bendy127** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to Mr John a whitehathacker who helped me recover all of it message him on telegram too t.me/Whitehathacker217

**Comment by Bendy127** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to Mr John a whitehathacker who helped me recover all of it message him on telegram too t.me/Whitehathacker217
