### ISSUE TITLE
Poollotto.finance (PLT) Is safe, audited by internal and external auditor 0x631c2f0edabac799f07550aee4ff0bf7fd35212b

### ISSUE THREAD

**Issue by bitgoalsdeveloper** [hashdit/hashdit#12]
we have been flagged as high risk project, but the data that was used for your analysis is incorrect and outdated. 
 - all the project tokens have been distributed, with over 30k holders.
-  all pre-sale investments that were locked for two years are now released and back in circulation for over 6 months now. 

could you please point me to the right person to speak to about this, as this has quite a negative impact on our project, which was launched over 2 years ago with a commitment to blockchain transparency and gaming fairness. 

the token is also whitelabel and used in 
https://poollotto.finance/
https://metalottery.win/
https://pltlotto.com/

if there any issues that can we need to solve please guide us and if not we need to be remove as soon as possible before we starting marketing campaign 

thanks,

**Comment by bitgoalsdeveloper** [comment]
Also you can see the auditing results:  
[https://github.com/Quillhash/QuillAudit_Reports/blob/master/Poollotto%20Smart%20Contract%20Audit%20Report%20-%20QuillAudits.pdf](url)

**Comment by bitgoalsdeveloper** [comment]
@a4dyn @web-flow @theexoticman @cryptocifer 
Can you please help ?

**Comment by slim115** [comment]
Hey team, apologies for the delay, could you assist with verifying this contract 0x8A6F7834A9d60090668F5db33FEC353a7Fb4704B on-chain before we proceed to fix this issue? Thank you for your understanding
