### ISSUE TITLE
Request for Unblocking Domain: https://zir.exchange/

### ISSUE THREAD

**Issue by laashad** [hashdit/hashdit#17]
We’re reaching out to request the unblocking of our domain https://zir.exchange/. 

Zir Exchange is an NFT marketplace and launchpad on Zircuit. We are not on BSC or Ethereum. Since our launch in June 2024, we have been operational and acquiring users without any evidence of our DApp engaging in malicious activity or impersonating any corporation.
 
For your reference, here are some supporting details:
- Our Twitter: https://x.com/zir_exchange
- Our Discord: https://discord.gg/SpFyCTX3VN
- ChainPatrol and SEAL-ISAC both set Zir Exchange as allowed: https://app.chainpatrol.io/search?content=zir.exchange

Please resolve this as soon as possible, as this not only affects us but also impacts the projects that are launching with us. We are happy to cooperate to resolve this issue!

Thank you

**Comment by laashad** [comment]
Could you please look into our case and resolve it? Thank you @a4dyn @slim115 @theexoticman @Wilson-Wu1

**Comment by slim115** [comment]
Hello @laashad, we have resolved the issue, which was caused by a third-party consumer we interacted with. Thank you for your understanding.

**Comment by laashad** [comment]
Thank you, we appreciate your support
