### ISSUE TITLE
Hashdit identifying bigeyes.space domain as unsafe

### ISSUE THREAD

**Issue by TeamAtBigeyes** [hashdit/hashdit#5]
Hello, 

We would like to request that the domain:

buy1.bigeyes.space 

is removed from your unsafe list. 

This is affecting our project and trust to the longevity of the project. We are developing new sections into our ecosystem and due to the unsafe listing of our domain listed above, trust wallet has identified it as "High Risk Detected" with a red banner. 

We have also emailed you and received no response. 

Awaiting you to get back and also removing us from your unsafe list. 

Regards 

Big Eyes

**Comment by MithOOnn** [comment]
0xBd6950E133ddfD72F19A90a755BaB3Da03260cc1
This address did phishing Attack 
![Screenshot_2024-01-23-04-19-23-24_08800057d42e3b72e31ae4fd4c41ba57](https://github.com/hashdit/hashdit/assets/126584786/a7b48201-9df0-4bc9-8adc-a557ca5c75ad)
