### ISSUE TITLE
Securechain.ai needs to be added to the whitelist 

### ISSUE THREAD

**Issue by sandipjoshi** [hashdit/hashdit#9]
This is not fair to the securechain community it is a legitimate project with a strong community. Please make sure to add it to your whitelist.

Check out the details on the securechain.ai
Contact: contact@securechain.ai for more info on project

**Comment by solidityx** [comment]
Yeah. Please unblock the legitimate website from your blocklist.

Securechain.ai is a legitimate project with large community.

Please check its social media for more details.

Thank you team

**Comment by yaschine** [comment]
In two month SecureChainAI in the market . Since entering to market community growing regularly. Securechain has own network. SecureChain are struglle with everything as a new project and there is this. 
You can ignore all the efford and say this: SecureChain not in the white list. What a Shame

**Comment by meliaa-4** [comment]
Securechain.ai is a nice project with large community. Please unblock the legitimate website from your blocklist.
Please check its social media for more details.
Thank you team

**Comment by paulydon** [comment]
Secure chain AI is a very serious project and needs all approvals, SCAI 🚀🚀

**Comment by probizz1** [comment]
securechain is a genuine and legitimate project with a strong community. kindly ensure to add it to your whitelist.

**Comment by probizz1** [comment]
sec

**Comment by luzo293** [comment]
securechain appears to be solid.

**Comment by Mymkwachiri** [comment]
Securechain is good project on 2023

**Comment by sandipjoshi** [comment]
@hashdit

**Comment by ertanizm35** [comment]
SecureChain on whitelist. They are good in crypto space

**Comment by AMFcryptos** [comment]
securechain ai is a legitimate project, with strong community and amazing utility. we urge you kindly add it to whitelist

**Comment by Gentledon33** [comment]
SecureChain AI is a community project , is safe and trusted you guys should whitelist  #SCAI this project  is strongly backed with a transparent team.

**Comment by Ediame1** [comment]
Whitelist SCAI it is the best and genuine project I have seen this year. Transparency, sincerity and a great community. Whitelist SCAI! White list SCAI!! Whitelist SCAI!!!

**Comment by yanx1987** [comment]
I personally, wetness the group Of SCAI, IS STRONG COMMUNITY, transparent, and the community people involved with it is nice, the team is transparent, white list SCAI...👍👍👍💯💯💯💯🥰🥰🥰🥰

**Comment by Arazazpi** [comment]
SCAI is real, not fake.
The SCAI community is real, not fake.
The SCAI project is real and not fake.
Please unblock
Please make sure to add it to your whitelist

@hashdit

**Comment by Mhwt1035** [comment]
Whitelist again. SecureChainAI is a good project

**Comment by emreozkan55** [comment]
SCAI gerçektir, sahte değil.
SCAI topluluğu sahte değil gerçektir.
SCAI projesi gerçektir, sahte değildir.
Lütfen engellemeyi kaldırın
Lütfen bunu beyaz listenize eklediğinizden emin olun.

@hashdit

**Comment by Monsterclass** [comment]
SecurechainAi is a legit project, and a good one with a great team

**Comment by wed30520888** [comment]
SecurechainAi 是一个合法的项目，而且是一个拥有优秀团队的好项目

**Comment by Philus94** [comment]
SCAI is a quality project....What the team is building is massive...It needs attention from all

**Comment by tomorad** [comment]
SCAI is a legitimate project.

Please register me on the whitelist!

**Comment by sndn58596** [comment]
You must register on the whitelist.
SCAI legit project!!

@hashdit

**Comment by skdjk888** [comment]
It is a legitimate project with many utilities.

We would appreciate it if you could register us on the whitelist again.

@hashdit

**Comment by clp19738** [comment]
Metamask has also been added to the whitelist.
Please re-register to the whitelist

**Comment by ujji0493** [comment]
SCAI is legit project!!

**Comment by yaschine** [comment]
You are adding black list in a minute but you dont do respond to apply 2 weeks. #scai is a legit project. Back to white list.

**Comment by lovedas213** [comment]
@Hashdit, I'm deeply concerned about false positives affecting securechain.ai. Let's unite to ensure accurate flagging and safeguard the integrity of blockchain projects

**Comment by paulydon** [comment]
Secure chain Ai should be top preriority

**Comment by lsolpo669** [comment]
SCAI is legit project!!

**Comment by apssld** [comment]
It should be removed from the blacklist.

I would appreciate it if you could consider it.

**Comment by sandipjoshi** [comment]
Dear community members, we are working with the hashdit team to resolve this issue both of our goals are to safeguard the interests of the users so i request everyone to support the hasdit and SecurechainAi in making our web3 ecosystem robust and scam free.
